### PR TITLE
Complexity module

### PR DESCRIPTION
**Pull request by hyruuk**
I just created a complexity module based on the spectral module + the NeuroKit toolbox. I tried to make it clean so it can be used as part of EEGsynth. For now, the code aims to compute SVD entropy, Higuchi's FD and Hurst exponent, but other metrics can be added easily (in complexity.py) if they are included in NeuroKit. Moreover, I chose to compute the metrics on averaged channels, so the signal is more robust and the code is less computationally intensive. 

Please let me know if you want me to modify something before pulling the new module to eegsynth's master branch.

Happy neurofeedback experiments !

### CODE REVIEW

**Comment by robertoostenveld** [comment]
Dear @hyruuk, sorry for it taking some time to look into your PR. First of all thanks for the contribution! I had a look at it, and tried it with a small test patch. Overall it looks like a very clean implementation and I had no issues in getting it to run.

I am not really familiar with these complexity metrics. Am I right that all complexity measures are computed on multidimensional data, i.e. on a matrix that is Nchannels * Ntimepoints? That seems the case, since you output only one scalar per measure. 

However, now looking in more detail in your code it seems that you are first averaging (over channels?) and then computing the measure. If that is the case, it would make more sense to compute the measure for each channel (like we compute RMS, spectral power, or historysignal for each channel), and rather implement the channel-averaging (which is a useful feature) elsewhere. The output would then become "channel1.higuchi" etc.

For the channel averaging: we once had re-referencing as part of the "preprocessing" module, but dropped that again since it was not used and the implementation was confusing. I think that this would be a reason to re-implement it. Rather than specific re-referencing (common average, bipolar, etc), I would then suggest to allow arbitrary linear combinations, which would also allow averaging.

Would you care to change the current implementation such that it outputs the measures per channel, as in the other modules? I can then look into the averaging/referencing.

**Comment by robertoostenveld** [comment]
Oh, something else: I noticed that you have made the changes to your master. That works for me, but might not be optimal for you. If I were to merge a modified version of your changes, your master would be hard to synchronize again with the eegsynth/master. Better practice for you would be to make the changes in a feature branch. You still might want to do that, i.e. make a branch of your master (with changes), and on your master itself revert to the latest commit that precedes your changes. Your master can then continue to follow ours.

**Comment by hyruuk** [comment]
Hi @robertoostenveld,

Thanks a lot for looking at my module !

Complexity measures can be computed on 1D time series. I did a quick and quite dirty averaging across channels so it would compute only one value, and thus save a bit of computation time (because I think that a good sampling frequency, say at least 5 to 10Hz is necessary for neurofeedback, and complexity metrics can be computationally intensive). However, I agree that this behaviour is not optimal, and it would be better to compute the complexity measures on each channel separately by default, and either add an option to average the channels (I find that since it's something we might often want to do, it can be useful to do it without relying on another module ?) or reimplement it elsewhere (which have the advantage of being more general).

I will modify the code so it behaves accordingly and then I'll get a bit of help from a friend to redo the pull request in a cleaner way.

Thanks again for your feedback !
Cheers

**Comment by robertoostenveld** [comment]
closed in favour of #351

**Pull request closed without merging**
