### PR TITLE
use 2to3 to convert the Python 2.7 to Python 3.x

### PR DESCRIPTION
**Pull request by robertoostenveld**
important for #309 is that the existing support for Python 2.7 does not break. 

After making the changes I tested it with one patch and python 2.7, and it seemed all to work. I did not have some hardware attached (launchcontrol, cvgate, eeg), so cannot confirm that everything works. 

There was one module (geomixer) that caused a problem with end-of-line differences and print, I solved that according to https://stackoverflow.com/questions/493386/how-to-print-without-newline-or-space.

@stephenwhitmarsh would you mind pulling this branch and testing it against your patch/setup, i.e. with your current python version and all of your current pip-installed packages? If this PR does not break things, it would already be a good step to improving support for Python 3.

### CODE REVIEW

**Comment by robertoostenveld** [comment]
For reference: I used this

    find eegsynth -name \*.py -exec 2to3 -n -w {} \;

See also https://docs.python.org/2/library/2to3.html

After this automatic conversion I only did some minor manual updates (geomixer, and comments regarding configparser).

**Comment by stephenwhitmarsh** [comment]
Super. Will do!

**Comment by stephenwhitmarsh** [comment]
Turns out:
Python2: ConfigParser
Python3: configparser
Sooo.. can't find the module now since it's renamed. Suggested change in all modules:

Try: 
    configparser
Except:
    ConfigParser

**Comment by robertoostenveld** [comment]
oh bummer, I don't think this was already at the stage for merging. Does everything still work with python2.7 as it used to do? If not, I have to be careful with the upcoming performance in Gothenburg (next weekend)

**Comment by stephenwhitmarsh** [comment]
I don't think we can be backwards compatible. Which won't be possible anyway with the upcoming redesign. So one suggestion is to just do the switch (but you stay on an old one for the next performance to be safe). For this we all have to upgrade to Python3. My PCs are ready thanks to anaconda. But I will have to set it up on my Linux laptop yet.

I've encountered several issues with unclear types (ongure types ;-)), since python3 is much more picky, and some changes in default behaviour e.g. in Redis. The biggest problem by far is the FT buffer issue which I have not been able to solve and blocks further development. I trust the rest of the conversion will only clarify things.

**Comment by robertoostenveld** [comment]
breaking backward compatible with old ini files is one thing, but all of a sudden not supporting python2 any more is a completely different thing. There is no reason to stop supporting python 2, since all python 3 code can (with some care) run under 2 as well.

**Comment by stephenwhitmarsh** [comment]
i follow you, but why do we care about supporting (a retiring) python2?

**Comment by stephenwhitmarsh** [comment]
however, if i keep my laptop at 2.7 I can test 3 on my pc's, otherwise it
will be hard to test both myself, and you should not be the gatekeeper for 2

**Comment by robertoostenveld** [comment]
Two reasons: 
1. A retiring python is not a retired python yet: end of 2020 is still far away. And python2 will not all of a sudden have disappeared in 2021. 
2. Currently users have eegsynth installed on their computers (e.g. I have it on 4 computers, and I am a research group that also use it): A single "git pull" is enough to break their work. Fixing it is a lot of work, and we don't even provide documentation for it. That will not be appreciate and those people might walk out on our code base.

**Comment by stephenwhitmarsh** [comment]
You're right, I forgot about the other people.

**Comment by robertoostenveld** [comment]
I suggest we see how to continue to work toward python3, but at the same time keep support for python2 for now. That means that we have to test it (occasionally) on both platforms. Perhaps you want to be the python3 tester, and I can be the python2 tester.

**Comment by stephenwhitmarsh** [comment]
I would personally prefer if you could also test 3, but that is because I
would like you to take a look at the FT buffer in 3 :-)

I can test in 3 for Windows (PCs), and 2 for Linux (laptop).

**Pull request merged**
