### PR TITLE
compatibility with namechange in python 3

### PR DESCRIPTION
**Pull request by stephenwhitmarsh**
Okay?

### CODE REVIEW

**Comment by robertoostenveld** [comment]
can you explain to me why this is needed? For me "import configparser" works fine both for 2 and 3.

**Comment by stephenwhitmarsh** [comment]
I doesn't for me! See answer here, I have the same issue:
https://stackoverflow.com/questions/14087598/python-3-importerror-no-module-named-configparser

**Comment by robertoostenveld** [comment]
So ConfigParser (with capitals) does not work for python3, but the current code uses configparser (without capitals) and that works both for 2 and 3.

For python2 we also should be using the new configparser, since otherwise the new options (like "inline_comment_prefixes") will not work.

**Comment by stephenwhitmarsh** [comment]
ah so you can install the new configparser (no capitals) on python 2? i see
how i can do that on my python 2 installation then

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by robertoostenveld** [comment]
It was installed by default for me with anaconda2.

**Comment by stephenwhitmarsh** [comment]
good for you, not with my Mint :-)

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by robertoostenveld** [comment]
Python folks always tell me that one should install anaconda and that it “automagically" works

**Comment by robertoostenveld** [comment]
See 
https://pypi.org/project/configparser/

**Comment by robertoostenveld** [comment]
@stephenwhitmarsh I just did a fresh install on JL's MacBook and ran into the configparser problem with the brew version of python2. It was solved after `sudo pip install configparser`

**Comment by stephenwhitmarsh** [comment]
Top. Noted.

**Pull request closed without merging**
