### PR TITLE
Bugfixes and cleanup of code + adding timing output for debugging

### PR DESCRIPTION
**Pull request by stephenwhitmarsh**
@deep-introspection @robertoostenveld:

It takes about 1.7 seconds to write one second to the second (wav) buffer on my new super-fast Ubuntu laptop. Debugging the timings, its clear this is taken up by writing to the buffer (1.6 seconds). Is this the same problem we encountered before, i.e. the localhost loopback?

If so, this might be the case with the postprocessing module as well?

### CODE REVIEW

**Comment by robertoostenveld** [comment]
I think this is indeed the same problem. Can you try writing over an ssh tunnel from localhost to localhost (i.e. with the data going over the tunnel)?

**Comment by stephenwhitmarsh** [comment]
Sure, could you please give me some tips on how to do so?

On 17 Jan 2018 6:59 p.m., "Robert Oostenveld" <notifications@github.com>
wrote:

I think this is indeed the same problem. Can you try writing over an ssh
tunnel from localhost to localhost (i.e. with the data going over the
tunnel)?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/eegsynth/eegsynth/pull/200#issuecomment-358388890>, or mute
the thread

**Comment by robertoostenveld** [comment]
From my phone and top of my head

ssh -L 1973:localhost:1873 localhost

This would connect port 1873 to 1973, which has the real buffer server. With eegsynth you connect to 1873.



Verstuurd vanaf mijn iPhone

**Comment by stephenwhitmarsh** [comment]
Hi Robert,

After I establish the tunnel as you describe (seems to work, no errors),
running the buffer gives me this error message:
Starting FieldTrip buffer on port 1972...
Starting FieldTrip buffer on port 1973...
tcpserver bind: Address already in use

Should I perhaps reverse the tunnel?

**Pull request merged**
