### PR TITLE
update of older stuff before starting on BBDMI

### PR DESCRIPTION
**Pull request by stephenwhitmarsh**

### CODE REVIEW

**Comment by robertoostenveld** [comment]
can you delete the `_backup` and `_deleted` version of generaterythm?

**Comment by robertoostenveld** [comment]
can you delete the `generatetrigger.ini` file from the generaterythm module?

**Comment by robertoostenveld** [comment]
can you merge the README.txt and README.md file in the LSLbandpower patch into a single readme?

**Comment by robertoostenveld** [comment]
For the WSL patch it would be nice if the README would contain a bit more detail, for example when this patch was used (either in performances, at events, or on youtube videos).

**Comment by robertoostenveld** [comment]
Please rename the anaconda patch. From the readme it seems that it was used at the 2019 InScience festival, so please use that as the patch name.  Please also merge the README.txt and README.md in a single file.

**Review by robertoostenveld — CHANGES_REQUESTED** [review]
this needs changes before it can be merged, see my comments for details.

**Comment by stephenwhitmarsh** [comment]
Can we cancel/close this PR please?

**Pull request closed without merging**
